### PR TITLE
Slight wording tweak to skaffold continuous development info label

### PR DESCRIPTION
**Pull request by etanshaul**
old:
image

new:
image

wdyt?

### CODE REVIEW

**Comment by etanshaul** [comment]
I wish there was an easy way to get the label to wrap properly. Currently it hides a portion of the text if the screen is made narrow enough.

**Comment by ivanporty** [comment]
It looks good, but about `specified Kubernetes cluster`, we don't choose one here (yet, until we have a selector for kubectl context), so could this be a bit misleading?

**Comment by etanshaul** [comment]
yeah good point. really, I want to say: `... to the Kubernetes cluster specified in your Skaffold configuration`

But thats too long. Thinking..

**Comment by etanshaul** [comment]
I guess I'll just keep it as:

```
Watches the dependencies of your docker image for changes, so that on any change, Skaffold builds and deploy your application to a Kubernetes cluster.
```

The same thing you had before except for `[a] Kubernetes cluster`. Sound ok for now?

**Pull request merged**
